name: FBase CI/CD pipeline
run-name: ${{ github.actor }} clean package
on: [push]
jobs:
  desktop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install maven
        run: apt-get update && apt-get install -y maven
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Check maven
        run: mvn -v
      - name: Build with maven
        run: mvn --no-transfer-progress clean package